Capitalise make file

diff --git a/demo/examples/Code-Generation/makefile b/demo/examples/Code-Generation/makefile
--- a/demo/examples/Code-Generation/makefile
+++ b/demo/examples/Code-Generation/makefile
@@ -3,7 +3,7 @@
 # `pip uninstall sysl` as make might be running an old sysl version
 
 TMP = .tmp# Cache the server lib directory in tmp
-
+SERVERLIB = /var/tmp
 TRANSFORMS=$(wildcard .tmp/server-lib/codegen/transforms/*.sysl)
 GRAMMAR=$(wildcard .tmp/server-lib/codegen/grammars/go.gen.g)
 START=goFile
@@ -12,27 +12,33 @@ APPNAME=Simple
 
 # Always execute these with just `make`
 .PHONY: download clean gen
-all: setup this
+all: setup gen clean
 
 # try to clone, then try to fetch and pull
 setup:
 	@echo --------------------------------------------------------
-	@echo Syncing server-lib ....
-	set -e
-	git clone https://github.service.anz/sysl/server-lib/ $(TMP)/server-lib || true  # Don't fail 
-	cd  $(TMP)/server-lib && git fetch && git pull && cd ../..
-	echo Fetching Success 
+	@echo Syncing server-lib to $(SERVERLIB)
+	@set -e
+	@git clone https://github.service.anz/sysl/server-lib/ $(SERVERLIB)/server-lib || true  # Don't fail 
+	@cd  $(SERVERLIB)/server-lib && git fetch && git pull && cd ../..
+	@mkdir -p $(TMP)/server-lib/
+	@echo Copying server-lib to $(TMP)
+	@cp -rf $(SERVERLIB)/server-lib $(TMP)/server-lib/
+	@echo Fetching Success 
 	@echo --------------------------------------------------------
 
 # Generate files with internal git service
 gen:
 	@echo --------------------------------------------------------
 	@echo Running sysl transforms ....
-	export GOPRIVATE="github.service.anz"
+	@export GOPRIVATE="github.service.anz"
 	$(foreach file, $(TRANSFORMS), $(shell sysl codegen --transform $(file) --grammar ${GRAMMAR} --start ${START} --outdir=output --app-name ${APPNAME} $(input)))
-	gofmt -s -w output/*
-	goimports -w output/*
+	@gofmt -s -w output/*
+	@goimports -w output/*
 	@echo --------------------------------------------------------
 
 clean:
+	@echo --------------------------------------------------------
+	@echo cleaning up $(TMP)
 	rm -rf $(TMP)
+	@echo --------------------------------------------------------
